import type { TextCoverElement } from './types'

export interface CoverTextPreset {
  id: string
  name: string
  previewText: string
  style: Partial<TextCoverElement>
}

export const COVER_TEXT_PRESETS: CoverTextPreset[] = [
  {
    id: 'special-promo',
    name: 'Special Promo',
    previewText: 'Special Promo',
    style: {
      text: 'Special Promo',
      color: '#a855f7',
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'bold',
      fontSize: 36,
      shadow: {
        enabled: true,
        color: '#a855f7',
        blur: 14,
        offsetX: 0,
        offsetY: 0,
      },
    },
  },
  {
    id: 'coffee-break',
    name: 'Coffee Break',
    previewText: '#Coffee Break',
    style: {
      text: '#Coffee Break',
      color: '#451a03',
      fontFamily: 'Impact, Arial Black, sans-serif',
      fontWeight: '900',
      fontSize: 34,
      stroke: {
        enabled: true,
        color: '#fef3c7',
        width: 2.5,
      },
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.85)',
        blur: 6,
        offsetX: 2,
        offsetY: 2,
      },
    },
  },
  {
    id: 'healthy-food',
    name: 'Healthy Food',
    previewText: 'Healthy Food',
    style: {
      text: 'Healthy Food',
      color: '#fef08a',
      fontFamily: 'Inter, sans-serif',
      fontWeight: '900',
      fontSize: 34,
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.6)',
        blur: 4,
        offsetX: 0,
        offsetY: 3,
      },
    },
  },
  {
    id: 'babytoy',
    name: 'BABYTOY',
    previewText: 'BABYTOY',
    style: {
      text: 'BABYTOY',
      color: '#facc15',
      fontFamily: 'Impact, Arial Black, sans-serif',
      fontWeight: '900',
      fontSize: 38,
      textTransform: 'uppercase',
      stroke: {
        enabled: true,
        color: '#18181b',
        width: 3,
      },
      shadow: {
        enabled: true,
        color: '#ca8a04',
        blur: 0,
        offsetX: 2,
        offsetY: 3,
      },
    },
  },
  {
    id: 'okay',
    name: 'okay.',
    previewText: 'okay.',
    style: {
      text: 'okay.',
      color: '#ffffff',
      fontFamily: 'Impact, Arial Black, sans-serif',
      fontWeight: '900',
      fontStyle: 'italic',
      fontSize: 40,
      stroke: {
        enabled: true,
        color: '#000000',
        width: 2,
      },
      shadow: {
        enabled: true,
        color: '#000000',
        blur: 0,
        offsetX: 4,
        offsetY: 4,
      },
    },
  },
  {
    id: 'love-it',
    name: 'Love it.',
    previewText: 'Love it.',
    style: {
      text: 'Love it.',
      color: '#f472b6',
      fontFamily: 'Playfair Display, Georgia, serif',
      fontWeight: '900',
      fontStyle: 'italic',
      fontSize: 38,
      stroke: {
        enabled: true,
        color: '#ffffff',
        width: 1.5,
      },
      shadow: {
        enabled: true,
        color: 'rgba(244, 114, 182, 0.7)',
        blur: 10,
        offsetX: 0,
        offsetY: 2,
      },
    },
  },
  {
    id: 'fresh-look',
    name: 'FRESH LOOK',
    previewText: 'FRESH LOOK',
    style: {
      text: 'FRESH LOOK',
      color: '#67e8f9',
      fontFamily: 'Impact, Arial Black, sans-serif',
      fontWeight: '900',
      fontSize: 36,
      textTransform: 'uppercase',
      letterSpacing: 1,
      stroke: {
        enabled: true,
        color: '#ffffff',
        width: 2,
      },
      shadow: {
        enabled: true,
        color: 'rgba(6, 182, 212, 0.8)',
        blur: 10,
        offsetX: 0,
        offsetY: 3,
      },
    },
  },
  {
    id: 'exclusive-jewelry',
    name: 'Exclusive Jewelry',
    previewText: 'Exclusive Jewelry',
    style: {
      text: 'Exclusive Jewelry',
      color: '#fbcfe8',
      fontFamily: 'Playfair Display, Georgia, serif',
      fontWeight: '600',
      fontSize: 22,
      letterSpacing: 2,
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.8)',
        blur: 6,
        offsetX: 0,
        offsetY: 2,
      },
    },
  },
  {
    id: 'neon-night',
    name: 'NEON NIGHT',
    previewText: 'NEON NIGHT',
    style: {
      text: 'NEON NIGHT',
      color: '#22d3ee',
      fontFamily: 'Inter, sans-serif',
      fontWeight: '900',
      fontSize: 36,
      textTransform: 'uppercase',
      letterSpacing: 2,
      shadow: {
        enabled: true,
        color: '#06b6d4',
        blur: 16,
        offsetX: 0,
        offsetY: 0,
      },
    },
  },
  {
    id: 'flash-sale',
    name: 'FLASH SALE',
    previewText: 'SALE 50%',
    style: {
      text: 'FLASH SALE 50%',
      color: '#ffffff',
      fontFamily: 'Impact, sans-serif',
      fontWeight: '900',
      fontSize: 34,
      backgroundColor: '#ef4444',
      stroke: {
        enabled: true,
        color: '#b91c1c',
        width: 1.5,
      },
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.8)',
        blur: 6,
        offsetX: 2,
        offsetY: 3,
      },
    },
  },
  {
    id: 'vlog-diary',
    name: 'Vlog Diary',
    previewText: 'Vlog Diary',
    style: {
      text: 'Vlog Diary ✨',
      color: '#ffffff',
      fontFamily: 'Caveat, cursive',
      fontWeight: 'bold',
      fontSize: 44,
      shadow: {
        enabled: true,
        color: '#000000',
        blur: 10,
        offsetX: 0,
        offsetY: 3,
      },
    },
  },
  {
    id: 'chill-vibes',
    name: 'CHILL VIBES',
    previewText: 'chill vibes',
    style: {
      text: 'chill vibes',
      color: '#a7f3d0',
      fontFamily: 'Inter, sans-serif',
      fontWeight: '800',
      fontSize: 32,
      letterSpacing: 1,
      stroke: {
        enabled: true,
        color: '#064e3b',
        width: 2,
      },
      shadow: {
        enabled: true,
        color: 'rgba(6, 78, 59, 0.6)',
        blur: 6,
        offsetX: 0,
        offsetY: 2,
      },
    },
  },
]
